var N=require("./EmptyState.css");const e=require("vue"),s=require("@smartmed/utility/consts"),m=require("../_plugin-vue_export-helper-f246444f.js"),d={analysis:`На${s.CHAR_NO_BREAK_SPACE}ближайшее время анализов
не${s.CHAR_NO_BREAK_SPACE}запланировано`,appointment:`На${s.CHAR_NO_BREAK_SPACE}ближайшее время приёмов
не${s.CHAR_NO_BREAK_SPACE}запланировано`,basket:"Корзина пока пуста",cards:"Привяжите банковскую карту, чтобы оплачивать консультации",clinics:`Мы${s.CHAR_NO_BREAK_SPACE}не${s.CHAR_NO_BREAK_SPACE}смогли найти клиники.
Попробуйте обновить страницу`,documents:`Здесь будут храниться все ваши
документы из${s.CHAR_NO_BREAK_SPACE}истории консультаций
с${s.CHAR_NO_BREAK_SPACE}врачами`,family:`Добавьте данные ваших близких,
чтобы заботиться об${s.CHAR_NO_BREAK_SPACE}их${s.CHAR_NO_BREAK_SPACE}здоровье`,notifications:"Уведомлений ещё нет",orders:"Пока нет заказов",referrals:`Врачи пока не${s.CHAR_NO_BREAK_SPACE}назначили
вам направлений`,support:`Здесь будут ваши обращения
в${s.CHAR_NO_BREAK_SPACE}техническую поддержку`},A={text:"",type:"appointment",src:""},E={key:0},y=["srcset"],C=["alt","src","srcset"],R=["alt","src"],S=e.defineComponent({name:"EmptyState",__name:"EmptyState",props:e.mergeDefaults({type:{},text:{},src:{}},A),setup(a){const l=a,{type:c,text:i,src:r}=e.toRefs(l),n=(t,o)=>`https://static.medsi.pro/images/${t}/pic@1x.${o} 1x, https://static.medsi.pro/images/${t}/pic@2x.${o} 2x`,u=e.computed(()=>{const t=i.value;if(t)return t;const o=c.value;return d[o]||""}),p=e.computed(()=>{const t=r.value;return t||`https://static.medsi.pro/images/${c.value}/pic@1x.png`}),_=e.computed(()=>{if(r.value)return{png:"",webp:""};const o=c.value;return{png:n(o,"png"),webp:n(o,"webp")}});return(t,o)=>(e.openBlock(),e.createElementBlock("div",{class:e.normalizeClass(["smed-text_body-xl",t.$style.root])},[e.renderSlot(t.$slots,"picture",{},()=>[e.unref(r)?(e.openBlock(),e.createElementBlock("img",{key:1,role:"presentation",decoding:"async",fetchpriority:"low",width:"104",height:"104",alt:e.unref(c),src:p.value,class:e.normalizeClass(["smed-space_bottom-6 smed-space_auto",t.$style.picture])},null,10,R)):(e.openBlock(),e.createElementBlock("picture",E,[e.createElementVNode("source",{type:"image/webp",srcset:_.value.webp},null,8,y),e.createElementVNode("img",{role:"presentation",decoding:"async",fetchpriority:"low",width:"104",height:"104",alt:e.unref(c),src:p.value,srcset:_.value.png,class:e.normalizeClass(["smed-space_bottom-6 smed-space_auto",t.$style.picture])},null,10,C)]))]),e.createElementVNode("span",null,[e.renderSlot(t.$slots,"text",{},()=>[e.createTextVNode(e.toDisplayString(u.value),1)])])],2))}}),$="_root_6chww_1",g="_picture_6chww_9",h={root:$,picture:g},B={$style:h},f=m._export_sfc(S,[["__cssModules",B]]);module.exports=f;
